stage2_4 = """
..................................
..................................
..................................
...........q......................
...........q......................
...........q......................
.s....G...kq.c..G.k...........d...
qqqqqqqqqqqqqqqqqqq......qqqqqqqqq
qqqqqqqqqqqqqqqqqqq......qqqqqqqqq
qqqqqqqqqqqqqqqqqqq......qqqqqqqqq
qqqqqqqqqqqqqqqqqqqkkkkkkqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
"""
