stage2_7 = """
...........................
...........................
...........................
...........................
.......................d...
......................qqqqq
...........................
.......s..qqqqqqqqqqqq.....
qk....gqqq..............qgq
qk....ggqq..............gqq
qk....pgqgj.k...........qqq
qk....gqgqqqq...........ggq
qk.c...j......J.........gqq
qqqqqqqqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqq
"""