chapter2 = """
................................
................................
................................
................................
....................5..6..qqqqqq
............3..4..qqqqqqqqqqqqqq
.s....1..2.qqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
"""