chapter1 = """
.....................................
.^.&.(..*............................
.....................................
...................5.................
..................ppp............8...
........2..3......ppp......7....ppp..
.s...1.ppppppp.4.JpppJ.6..ppp..ppppp.
ppppppppppppppppppppppppppppppppppppp
ppppppppppppppppppppppppppppppppppppp
"""