chapter1 = """
........................................
.^.&.(..*...............................
........................................
...................5....................
..................ppp...............9...
........2..3......ppp......7.......ppp..
.s...1.ppppppp.4.JpppJ.6..ppp..8..ppppp.
pppppppppppppppppppppppppppppppppppppppp
pppppppppppppppppppppppppppppppppppppppp
"""