main_menu = """
................................
................................
................................
................................
................................
...............2................
.s.....1....qqqqqqqqqqqqqqqqqqqq
ppppppppppppqqqqqqqqqqqqqqqqqqqq
pppppppppppqqqqqqqqqqqqqqqqqqqqq
"""