from Entity.Platform import Platform
from Entity.KillPlatform import KillPlatform
from Entity.CheckPoint import CheckPoint
from Entity.Cannon import Cannon
from Item.JumpItem import JumpItem
from Stages.parser import parse_stage
from constants import SCREEN
import pygame as pg


stage1 = parse_stage("""
.............................................
.............................................
...........................c.................
........................ppppppp..............
........................p.....p........pppppp
..................c...J.p.....p........p.....
.................pppppppp.....p........k.....
.s........c......p............p........k.....
ppppkkkkkpppppkkkp............pkkkkkkkkk.....
.............................................
""")


stage2 = parse_stage("""
................p...............
................p...............
kkkkkkkkkkkkkkkkk........ppppppp
................................
................................
........j.......................
p.....ppppppppp........kkkkkkkkk
p.....p.........J...J..p........
p.....p................p........
.......................p........
..................J....p........
.......................p........
....pp.................p........
pppppk......c...J......p........
pppppk....pppppppppppppppppppppp
pppppk....k.....................
....pp....k.....................
..........k.....................
.s........k.....................
pppppppppppppppppppppppppppppppp
................................
""")

stage3 = parse_stage("""
........................p........................
........................p............j...........
pppppppppppppppppkkkkkkkk....................pppp
.................................................
.......................................J.........
....................................J..kkkkkkkkkk
.............c..............c..........p.........
............pppppJJJJJJJJJppppppppJpppppppppppppp
............p....................................
............p....................................
.s...j......p....................................
pppppppppkkkppppppppppppppppppppppppppppppppppppp
""")

stage4 = parse_stage("""
pppppppppp..............p
pppppppppp..............p
pppppppppp..s...........p
pppppppppppppppp........p
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
pppppppppp.....kkkkkkkkkp
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
ppppppppppkkkkkkkkk.....p
p.......................p
p.......................p
p....................c..p
p..................pppppp
p......k...k...k........p
p......p...p...p........p
p......p...p...p........p
p......ppppppppppppppppppp
p.......k.....k.........p
p.......................p
p.c........k.....k......p
ppppppppppppppppppppppppp
""")

stage5 = parse_stage("""
....................................................
....................................................
....................................................
.............................pppppppp...............
.............................g......p...............
........pppppp...............p......p...............
........g....p...............p......p...............
........p....p...............p......p...............
........g....p...............g......p...............
.s......p....p...c....j......p......p...............
pppppppppppppppppppppppppppppppppppppppppppppppppppp
""")