stage1_2 = """
.......................................
.......................................
......................c................
...................ppppppp.............
...................ppppppp..........d..
.............c...J.ppppppp........ppppp
...........ppppppppppppppp........ppppp
...........ppppppppppppppp.......kppppp
.s.......kkppppppppppppppp.......kppppp
ppppppppppppppppppppppppppkkkkkkkkppppp
ppppppppppppppppppppppppppppppppppppppp
"""
