stage1_2 = """
pppppppppppppppppp..............
pppppppppppppppppp...........d..
..............kkkk.......ppppppp
................................
........j.......................
p.....ppppppppp........kkkkkkkkk
p...............J...J..ppppppppp
.......................ppppppppp
..................J....ppppppppp
....pppp...............ppppppppp
ppppppk.....c...J......ppppppppp
ppppppk...kppppppppppppppppppppp
ppppppk...kppppppppppppppppppppp
ppppppk...kppppppppppppppppppppp
..........kppppppppppppppppppppp
.s.........ppppppppppppppppppppp
pppppppppppppppppppppppppppppppp
pppppppppppppppppppppppppppppppp
"""
