stage1_4 = """
pppppppppp..............p
pppppppppp..............p
pppppppppp..s...........p
pppppppppppppppp........p
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
pppppppppp.....kkkkkkkkkp
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
ppppppppppkkkkkkkkk.....p
p.......................p
p.......................p
p....................c..p
p..................pppppp
p......k...k...k........p
p......p...p...p........p
p......p...p...p........p
p......ppppppppppppppppppp
p.......k.....k.........p
p.......................p
p.c........k.....k...d..p
ppppppppppppppppppppppppp
"""
