stage1_4 = """
pppppppppp..............p
pppppppppp..............p
pppppppppp..s...........p
pppppppppppppppp........p
ppppppppppppppppp.......p
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
pppppppppp.....kkkkkkkkkp
pppppppppp.....pppppppppp
pppppppppp..............p
pppppppppp..............p
pppppppppp..............p
ppppppppppkkkkkkkkk.....p
ppppppppppppppppppp.....p
pp......................p
pp......................p
pp...................c..p
pp.................pppppp
pp.....k...k...k........p
pp.....p...p...p........p
pp.....p...p...p........p
pp.....ppppppppppppppppppp
pp......k.....k.........p
pp......................p
pp.c.......k.....k...d..p
ppppppppppppppppppppppppp
"""
