stage1_7 = """
........p..p..p.....................................
........p..p..p.....................................
........p..p..p.....................................
........p..p..p.....................................
........p..p..p.............k.......................
........p..p..p........k....pk......................
........p..p.....d.....pk...........................
........p.....ppppp............J...............c....
...........pp.................pppppkkppkkppppppppppp
.s......pp................p....ppppppppppppppppppppp
ppppppk...............p.......kppppppppppppppppppppp
ppppppk...................k.pppppppppppppppppppppppp
ppppppk..........c....k.pppppppppppppppppppppppppppp
pppppp.pppkppkpppppppppppppppppppppppppppppppppppppp
pppppp.ppppppppppppppppppppppppppppppppppppppppppppp
"""
