stage1_2 = """
pppppppppppppppppp..............
pppppppppppppppppp...........d..
..............kkkk.......ppppppp
................................
........j.......................
p.....ppppppppp........kkkkkkkkk
p...............J...J..ppppppppp
.......................ppppppppp
.......................ppppppppp
.......ppp........J....ppppppppp
......pppp.............ppppppppp
.....pp................ppppppppp
pppppppk....c...J......ppppppppp
pppppppk..kppppppppppppppppppppp
pppppppk..kppppppppppppppppppppp
pppppppk..kppppppppppppppppppppp
..........kppppppppppppppppppppp
.s.........ppppppppppppppppppppp
pppppppppppppppppppppppppppppppp
pppppppppppppppppppppppppppppppp
"""
